# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='drone_category',
            new_name='drones_category',
        ),
    ]
