# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20180426_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='drones_category',
        ),
        migrations.AlterField(
            model_name='competition',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='drones.Pilot'),
        ),
    ]
